#ARMA Process

#In order p AR process sum of thetas <1 and abs(theta_p) < 1

#In ar process  theta1 + theta2 < 1, theta1 - theta2 < 1, abs(theta2) < 1
arma<-arima.sim(model=list(ar=c(0.5,0.4),ma=(0.3)),n=100)

#To see data generated by process
arma

#Create empty plot
dev.new()

#Plot the data
plot(arma,type='o')

#Close the plot
dev.off()



