#Moving Average Process

#For MA1 pass 1 argument in list
ma1<-arima.sim(model=list(ma=c(0.5)),n=100)

#To see data generated by process
ma1

#Create empty plot
dev.new()

#Plot the data
plot(ma1,type='o')

#Close the plot
dev.off()


#For MA2 pass 2 argument in list
ma2<-arima.sim(model=list(ma=c(0.5,0.6)),n=100)

#To see data generated by process
ma2

#Create empty plot
dev.new()

#Plot the data
plot(ma2,type='o')

#Close the plot
dev.off()

#And so on for general MA order n process
