#Whitenoise
#passing empty list to model will generate white noise
wn<-arima.sim(model=list(),n=100)

#To see data generated by process
wn

#Create empty plot
dev.new()

#Plot the data
plot(wn,type='o')

#Close the plot
dev.off()
